### PR TITLE
Change audio lib + add tox (supporting Python >= 3.7)

### PR DESCRIPTION
**Pull request by bbelderbos**

### CODE REVIEW

**Comment by Timfrazer** [comment]
1) readme is incorrect- there is no `make install` should be `make setup`
2) could probably just run `tox`  rather than pytest directly no?
However, the code works well on my system so just being picky

**Review by Timfrazer — CHANGES_REQUESTED** [review]
update the readme per my comments then I'll give you a 👍🏼

**Comment by bbelderbos** [comment]
Thanks @Timfrazer done and done. I also added the `pip install` instruction.

**Review by Timfrazer — APPROVED** [review]
Looks good 🥳

**Pull request merged**
